"https://{all}/":
  type: upstream
  upstream: "drupal:http"
  cache:
    enabled: false
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"https://www.{all}/":
  type: redirect
  to: "https://{all}/"
  
"https://{default}/slides":
  type: upstream
  upstream: "app:http"
  cache:
    enabled: true
  passthru: "/slides/"